### ISSUE TITLE
Example fails

### ISSUE THREAD

**Issue by ElectricCookie** [accounts-js/examples#8]
In the example the line
`app.use(accountsExpress(AccountsServer));`

fails with the following Exception:

```js
\node_modules\@accounts\rest-express\lib\index.js:117
          var _ref$path = _ref.path,
                              ^
TypeError: Cannot read property 'path' of undefined
```

Writing  `app.use(accountsExpress(AccountsServer,{}));` fixes this.

**Comment by cesarve77** [comment]
+1
